export default {
  LOAD_EVENTS_START: 'LOAD_EVENTS_START',
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENTS_ERROR: 'LOAD_EVENTS_ERROR',

  LOAD_EVENT_START: 'LOAD_EVENT_START',
  LOAD_EVENT_SUCCESS: 'LOAD_EVENT_SUCCESS',
  LOAD_EVENT_ERROR: 'LOAD_EVENT_ERROR',

  LOAD_ALL_EVENTS_START: 'LOAD_ALL_EVENTS_START',
  LOAD_ALL_EVENTS_SUCCESS: 'LOAD_ALL_EVENTS_SUCCESS',
  LOAD_ALL_EVENTS_ERROR: 'LOAD_ALL_EVENTS_ERROR',

  SETUP_EVENTS: 'SETUP_EVENTS',
  SETUP_EVENTS_LIST: 'SETUP_EVENTS_LIST',

  UPDATE_SOURCES: 'UPDATE_SOURCES',
  TOGGLE_SOURCES: 'TOGGLE_SOURCES',
  SETUP_SOURCES: 'SETUP_SOURCES',

  // LOAD_EVENT_ERROR: 'LOAD_EVENT_ERROR',

  RESET_EVENTS: 'RESET_EVENTS',
};
