export default {
  LOAD_EVENTS_START: 'LOAD_EVENTS_START',
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENTS_ERROR: 'LOAD_EVENTS_ERROR',

  LOAD_EVENT_START: 'LOAD_EVENT_START',
  LOAD_EVENT_SUCCESS: 'LOAD_EVENT_SUCCESS',
  LOAD_EVENT_ERROR: 'LOAD_EVENT_ERROR',
};
